## Les 'Makefile' ont énormément d'avantages et nous permettent de compiler des fichiers en grande quantités,
## dans plusieurs dossiers à la fois.

bt:	basic_test.c
	gcc	-o	bt	basic_test.c

## Il suffit de taper 'make' dans le dossier 'pwd' (répertoire de travail actuel)
## Ceci est un Makefile de niveau 0, il est très simple.
## A noter qu'un Makefile s'écrit avec des indentations un peu comme en python.

## On commence avec le nom de notre exécutable 'bt: ' puis le ou les fichiers en rapport.
## Ensuite la commande de compilation.